plugins {
    id "com.android.application"
}

android {
    namespace "com.lumina.todo"
    compileSdk 34

    defaultConfig {
        applicationId "com.lumina.todo"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("lumina.keystore")
            storePassword "luminaaraf"
            keyAlias "lumina"
            keyPassword "luminaaraf"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt")
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ["/META-INF/{AL2.0,LGPL2.1}"]
        }
    }
}

dependencies {
}
